---
title: "Bayesian Statistics - Final Assignment"
author: "Florian Metwaly"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(Hotelling)
source("sampler.R")
```

```{r}
# load in generated data
load("../data/population.RData")
```

# Sample PS
```{r}
set.seed(1337)
PS <- pop %>%
  slice_sample(n = 500)
```

# Sample NPS
```{r}
set.seed(1337)
NPS <- pop %>%
  mutate(weight = ifelse(X2 == 1, 1.3, 1)) %>%
  slice_sample(n = 2000, weight_by = weight)
```

```{r}
rm(pop) #remove object that is not used anymore
```

```{r}
res <- MHS(PS = PS, 
           NPS = NPS, 
           n.iter = 10000, 
           b0 = 1, 
           b1 = 2, 
           b2 = 3, 
           v0 = 3, 
           m0 = 0, 
           s0 = 2.5, 
           n.chains = 3, 
           seed = 1337) # run sampler

estimates <- rbind(res[[1]][3000:10000,], res[[2]][3000:10000,], res[[3]][3000:10000,]) # remove burn in
```


```{r}
# calculate estimates and credible intervals
mean(estimates$b0)
quantile(estimates$b0, c(0.025, 0.975))
mean(estimates$b1)
quantile(estimates$b1, c(0.025, 0.975))
mean(estimates$b2)
quantile(estimates$b2, c(0.025, 0.975))
```

```{r}
# calculate MSE
bias_b0 <- 0.5 - mean(estimates$b0)
bias_b1 <- 0.8 - mean(estimates$b1)
bias_b2 <- 0.3 - mean(estimates$b2)

var_b0 <- var(estimates$b0)
var_b1 <- var(estimates$b1)
var_b2 <- var(estimates$b2)

(MSE_b0 <- bias_b0^2 + var_b0)
(MSE_b1 <- bias_b1^2 + var_b1)
(MSE_b2 <- bias_b2^2 + var_b2)
```

# Plot convergence
```{r}
# Define the colors for each chain
colors <- c("blue", "red", "green")

png(filename = "../results/trace_plot_b0.png")
# Create an empty plot with labels and limits
plot(res[[1]]$b0, type = "l", col = colors[1], 
     xlab = "Iteration", ylab = "Value", 
     main = "Trace Plot b0", ylim = range(c(res[[1]]$b0, res[[2]]$b0, res[[3]]$b0)))

# Add second and 3rd chain
lines(res[[2]]$b0, col = colors[2])
lines(res[[3]]$b0, col = colors[3])

# Add a legend
legend("bottomright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = colors, lty = 1)
dev.off()
```

```{r}
png(filename = "../results/trace_plot_b1.png")
# Create an empty plot with labels and limits
plot(res[[1]]$b1, type = "l", col = colors[1], 
     xlab = "Iteration", ylab = "Value", 
     main = "Trace Plot b1", ylim = range(c(res[[1]]$b1, res[[2]]$b1, res[[3]]$b1)))

# Add second and 3rd chain
lines(res[[2]]$b1, col = colors[2])
lines(res[[3]]$b1, col = colors[3])

# Add a legend
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = colors, lty = 1)
dev.off()
```

```{r}
png(filename = "../results/trace_plot_b2.png")
# Create an empty plot with labels and limits
plot(res[[1]]$b2, type = "l", col = colors[1], 
     xlab = "Iteration", ylab = "Value", 
     main = "Trace Plot b2", ylim = range(c(res[[1]]$b2, res[[2]]$b2, res[[3]]$b2)))

# Add second and 3rd chain
lines(res[[2]]$b2, col = colors[2])
lines(res[[3]]$b2, col = colors[3])

# Add a legend
legend("topright", legend = c("Chain 1", "Chain 2", "Chain 3"), 
       col = colors, lty = 1)
dev.off()
```
# calc acceptance rate
```{r}
mean(c(res[[1]]$b0_acc, res[[1]]$b0_acc, res[[1]]$b0_acc))
mean(c(res[[1]]$b1_acc, res[[1]]$b1_acc, res[[1]]$b1_acc))
mean(c(res[[1]]$b2_acc, res[[1]]$b2_acc, res[[1]]$b2_acc))
```

# calc autocrrelation
```{r}
acf_results1 <- acf(res[[1]]$b0)
acf_results2 <- acf(res[[2]]$b0)
acf_results3 <- acf(res[[3]]$b0)

(mean(acf_results1$acf[-1]) + mean(acf_results2$acf[-1]) + mean(acf_results3$acf[-1]))/3

acf_results1 <- acf(res[[1]]$b1)
acf_results2 <- acf(res[[2]]$b1)
acf_results3 <- acf(res[[3]]$b1)

(mean(acf_results1$acf[-1]) + mean(acf_results2$acf[-1]) + mean(acf_results3$acf[-1]))/3

acf_results1 <- acf(res[[1]]$b2)
acf_results2 <- acf(res[[2]]$b2)
acf_results3 <- acf(res[[3]]$b2)

(mean(acf_results1$acf[-1]) + mean(acf_results2$acf[-1]) + mean(acf_results3$acf[-1]))/3
```


# Hypothesis testing
testing my estimated parameters against the population parameters.


```{r}
library(bain)
```

```{r}
#h0: b0_hat = 0.5
#ha: b0_hat =/= 0.5

n <- nrow(PS)+nrow(NPS)

sigma <- var(estimates$b0)

est <- mean(estimates$b0)
names(est) <- "b0"

# Perform Bayesian hypothesis testing
bain_result <- bain(est, hypothesis = "b0 = 0.5", n = n, Sigma = sigma)

print(bain_result)
```

```{r}
#h0: b1_hat = 0.8
#ha: b1_hat =/= 0.8

n <- nrow(PS)+nrow(NPS)

sigma <- var(estimates$b1)

est <- mean(estimates$b1)
names(est) <- "b1"

# Perform Bayesian hypothesis testing
bain_result <- bain(est, hypothesis = "b1 = 0.8", n = n, Sigma = sigma)

print(bain_result)
```

```{r}
#h0: b2_hat = 0.3
#ha: b2_hat =/= 0.3

n <- nrow(PS)+nrow(NPS)

sigma <- var(estimates$b2)

est <- mean(estimates$b2)
names(est) <- "b2"

# Perform Bayesian hypothesis testing
bain_result <- bain(est, hypothesis = "b2 = 0.3", n = n, Sigma = sigma)

print(bain_result)
```

